const MOTIVATIONAL_QUOTES = [
  'Hoy es un buen día para moverte 💪',
  'Un paso a la vez también es progreso.',
  'Tu cuerpo puede, tu mente es la que decide.',
  'Entrena por la salud, el cuerpo viene por añadidura.',
  'No tienes que ser el mejor, solo ser constante.',
  'Un entrenamiento es mejor que ningún entrenamiento.',
  'Hazlo por ti, por tu versión del futuro.',
  'Pequeños hábitos crean grandes cambios.',
  'Hoy te vas a agradecer no haberte rendido.',
  'Solo te arrepentirás del entrenamiento que no hiciste.',
  'Disciplina es hacer lo que dijiste que harías, incluso sin ganas.',
  'Tu único rival eres tú de ayer.',
  'Muévete por amor propio, no por castigo.',
  'Cinco minutos de movimiento valen más que cero.',
  'Tu cuerpo es tu casa, cuídala todos los días.',
  'Estás a un entrenamiento de mejorar tu ánimo.',
  'No busques perfección, busca consistencia.',
  'Aunque sea poquito, hoy también cuenta.',
  'Respira, mueve el cuerpo y celebra que puedes hacerlo.',
  'Cada día activo es un “sí” a tu bienestar.',
  'No esperes motivación, crea disciplina.',
  'Lo difícil hoy, mañana será tu calentamiento.',
  'Tu energía crece cuando te mueves.',
  'Sudar hoy es sonreír mañana.',
  'No se trata de ir rápido, se trata de no parar.',
  'Cada repetición cuenta, incluso las que cuestan.',
  'El progreso no se grita, se entrena.',
  'Entrenar también es una forma de quererte.',
  'Si no puedes con todo, empieza con algo.',
  'Más fuerte que ayer, más cerca que nunca.',
  'Tu mejor versión se construye entrenamiento a entrenamiento.',
  'La constancia vence al talento cuando el talento no se mueve.',
  'Hoy duele, mañana te enorgullece.',
  'No necesitas ganas, necesitas empezar.',
  'El gimnasio no cambia tu vida en un día, pero sí cada día.',
  'Cuando dudas, entrena.',
  'Haz del movimiento un hábito, no una excepción.',
  'Cada gota de esfuerzo suma resultados.',
  'No abandones por cansancio, descansa y continúa.',
  'La meta no es ser perfecto, es ser mejor.',
  'El cambio empieza cuando decides no rendirte.',
  'Tu salud es la mejor inversión que puedes hacer.',
  'Hoy entrenas por resultados que aún no ves.',
  'Mantente en movimiento: cuerpo fuerte, mente clara.',
  'Entrena tu cuerpo y también tu carácter.',
  'No compares tu inicio con el avance de otros.',
  'Constancia hoy, confianza mañana.',
  'Nadie puede hacer tus repeticiones por ti.',
  'Hazlo cansado, hazlo con miedo, pero hazlo.',
  'Cada entrenamiento es un voto por la persona que quieres ser.',
];

export const getRandomMotivationalQuote = () => {
  const index = Math.floor(Math.random() * MOTIVATIONAL_QUOTES.length);

  return MOTIVATIONAL_QUOTES[index];
};
