export const ROUTES = {
  login: '/login',
  register: '/register',
  onboarding: '/onboarding',
  home: '/home',
  workouts: '/workouts',
  trainers: '/trainers',
  profile: '/profile',
  support: '/support',
  subscription: '/subscription',
  premiumFeatures: '/premium-features',
  macrosCalculator: '/macros-calculator',
  diets: '/diets',
  routines: '/routines',
  contracts: '/contracts',
  trainerReviews: '/trainer-reviews',
  trainerClients: '/trainer-clients',
  trainerPayments: '/trainer-payments',
} as const;
