export const TRANSLATIONS = {
  welcomeScreen: {
    header: '¡Bienvenido a FITECH!',
    subheader: 'Tu mejor versión está a punto de activarse.',
    createAccountButton: 'Crear cuenta',
    logInButton: 'Iniciar sesión',
  },
  loginScreen: {
    header: 'Inicia sesión en tu \ncuenta',
    subheader: 'Entrena. Mejora. Repite.',
    loginGoogleButton: 'Continuar con Google',
    loginButton: 'Iniciar sesión',
    loginLoadingButton: 'Iniciando sesión…',
    forgotPasswordLink: '¿Olvidaste tu contraseña?',
    alternativeLoginCaption: 'O inicia sesión con',
    loginErrorFallback:
      'Ocurrió un error al iniciar sesión. Inténtalo nuevamente.',
  },
  registerScreen: {
    nextButton: 'Siguiente',
    createAccountButton: 'Crear cuenta',
    creatingAccountButton: 'Creando tu cuenta…',
    registerErrorFallback:
      'No pudimos crear tu cuenta. Revisa los datos e inténtalo de nuevo.',
    successTitle: '¡Cuenta creada!',
    successMessage:
      'Tu cuenta fue creada correctamente. Revisa tu correo electrónico y confirma tu cuenta antes de iniciar sesión.',
    successButton: 'Ir a iniciar sesión',
    cancelRegisterButton: 'Cancelar registro',
    cancelRegisterTitle: '¿Abandonar registro?',
    cancelRegisterMessage:
      'Saldrás del proceso de registro. Los datos que ingresaste no se guardarán.',
    cancelRegisterStay: 'Seguir registrándome',
    cancelRegisterLeave: 'Salir',
  },
  verifyEmailScreen: {
    title: 'Verifica tu correo',
    verifying: 'Verificando tu correo electrónico…',
    successTitle: '¡Correo verificado!',
    successMessage:
      'Tu cuenta ha sido verificada correctamente. Ya puedes iniciar sesión.',
    missingToken:
      'El enlace de verificación no es válido. Revisa el correo e inténtalo de nuevo.',
    errorFallback:
      'No pudimos verificar tu correo. Inténtalo de nuevo en unos minutos.',
    invalidToken:
      'Este enlace no es válido o ya expiró. Si ya verificaste tu correo, inicia sesión. Si no, revisa tu bandeja y abre el enlace más reciente.',
    goToLogin: 'Ir a iniciar sesión',
    retryButton: 'Reintentar',
  },
  forgotPasswordScreen: {
    title: '¿Olvidaste tu contraseña?',
    description:
      '¡No te preocupes! Ingresa el correo asociado a tu cuenta y te enviaremos instrucciones para restablecerla.',
    emailLabel: 'Correo electrónico',
    emailPlaceholder: 'tu@correo.com',
    submitButton: 'Enviar',
    emailRequired: 'Ingresa tu correo electrónico.',
    emailInvalid: 'Ingresa un correo electrónico válido.',
    successTitle: 'Revisa tu correo',
    successMessage:
      'Si existe una cuenta con ese correo, recibirás instrucciones para restablecer tu contraseña.',
    errorFallback:
      'No pudimos enviar el correo. Inténtalo de nuevo en unos minutos.',
  },
  changePasswordScreen: {
    title: 'Cambiar contraseña',
    introTitle: 'Antes de continuar',
    introBody:
      'Por seguridad, al cambiar tu contraseña cerraremos tu sesión en este dispositivo. Deberás iniciar sesión de nuevo con tu nueva contraseña.',
    currentPasswordLabel: 'Contraseña actual',
    currentPasswordPlaceholder: 'Tu contraseña actual',
    newPasswordLabel: 'Nueva contraseña',
    newPasswordPlaceholder: 'Mínimo 6 caracteres',
    confirmPasswordLabel: 'Confirmar nueva contraseña',
    confirmPasswordPlaceholder: 'Repite la nueva contraseña',
    submitButton: 'Cambiar',
    cancelButton: 'Cancelar',
    currentRequired: 'Ingresa tu contraseña actual.',
    passwordRequired: 'Ingresa tu nueva contraseña.',
    passwordTooShort: 'La contraseña debe tener al menos 6 caracteres.',
    confirmRequired: 'Confirma tu nueva contraseña.',
    passwordsMismatch: 'Las contraseñas no coinciden.',
    sameAsCurrent: 'La nueva contraseña debe ser distinta a la actual.',
    confirmTitle: '¿Cambiar contraseña?',
    confirmMessage:
      'Se cerrará tu sesión y tendrás que iniciar sesión con la nueva contraseña.',
    confirmAction: 'Sí, cambiar',
    confirmCancel: 'No, volver',
    successTitle: 'Contraseña actualizada',
    successMessage: 'Inicia sesión con tu nueva contraseña.',
    successButton: 'Ir a iniciar sesión',
    errorFallback:
      'No pudimos cambiar tu contraseña. Verifica la contraseña actual e inténtalo de nuevo.',
  },
  deleteAccountScreen: {
    title: 'Eliminar cuenta',
    introTitle: 'Esta acción es permanente',
    bullets: [
      'Se eliminará tu perfil, fotos y datos personales.',
      'Perderás acceso a rutinas, dietas, contratos y chats asociados a tu cuenta.',
      'Las suscripciones o contratos activos pueden cancelarse según las políticas de la plataforma.',
      'No podrás recuperar la cuenta después de confirmar.',
    ],
    note: 'Al confirmar, tu cuenta se eliminará de forma permanente.',
    cancelButton: 'Cancelar',
    confirmButton: 'Eliminar mi cuenta',
    confirmTitle: '¿Eliminar tu cuenta?',
    confirmMessage:
      'Esta acción no se puede deshacer. Se borrarán tus datos y cerrarás sesión.',
    confirmAction: 'Sí, eliminar',
    confirmCancel: 'No, volver',
    deletingButton: 'Eliminando cuenta…',
    successTitle: 'Cuenta eliminada',
    successMessage:
      'Tu cuenta fue eliminada correctamente. Gracias por haber usado FITECH.',
    successButton: 'Cerrar',
    errorFallback:
      'No pudimos eliminar tu cuenta. Inténtalo de nuevo en unos minutos.',
  },
  resetPasswordScreen: {
    title: 'Nueva contraseña',
    description: 'Elige una contraseña segura para tu cuenta.',
    passwordLabel: 'Nueva contraseña',
    passwordPlaceholder: 'Mínimo 6 caracteres',
    confirmPasswordLabel: 'Confirmar contraseña',
    confirmPasswordPlaceholder: 'Repite tu contraseña',
    submitButton: 'Guardar contraseña',
    passwordRequired: 'Ingresa tu nueva contraseña.',
    passwordTooShort: 'La contraseña debe tener al menos 6 caracteres.',
    confirmRequired: 'Confirma tu nueva contraseña.',
    passwordsMismatch: 'Las contraseñas no coinciden.',
    missingToken:
      'El enlace para restablecer la contraseña no es válido. Solicita uno nuevo desde “¿Olvidaste tu contraseña?”.',
    successTitle: '¡Contraseña actualizada!',
    successMessage: 'Ya puedes iniciar sesión con tu nueva contraseña.',
    errorFallback:
      'No pudimos actualizar tu contraseña. Inténtalo de nuevo en unos minutos.',
    invalidToken:
      'Este enlace no es válido o ya expiró. Solicita un nuevo correo de recuperación.',
    goToLogin: 'Ir a iniciar sesión',
  },
  userActivitiesSection: {
    sectionTitle: 'Mis actividades',
    emptyTitle: 'Tus planes, en un solo lugar',
    emptyBody:
      'Contrata un entrenador para recibir rutina y dieta personalizadas. Cuando te las asigne, las verás aquí.',
    findTrainersButton: 'Ver entrenadores',
    trainerLabel: 'Entrenador:',
    dietBadge: 'Dieta',
    routineBadge: 'Rutina',
    viewDetail: 'Ver detalle',
    defaultTitle: 'Mi plan',
    trainerSubtitle: 'Entrenador: {name}',
    validitySubtitle: 'Vigencia: {range}',
  },
  chatContractBanner: {
    clientTitle: 'Tu entrenador FITECH',
    clientSubtitle: 'Chat de seguimiento de tu plan activo',
    trainerTitle: 'Cliente con plan activo',
    trainerSubtitle: 'Chat de seguimiento FITECH',
  },
  matchCelebration: {
    gymbroTitle: '¡Es un match!',
    gymbroSubtitle:
      'Tú y {name} son GymBros. Arma hora y rutina — el entrenamiento pesa menos en equipo.',
    gymcrushTitle: '¡Es un match!',
    gymcrushSubtitle:
      'Tú y {name} se gustaron. Rompan el hielo con un plan y vean si hay química.',
    viewMatches: 'Ver mis matches',
    continue: 'Seguir descubriendo',
  },
  homePremiumWelcome: {
    title: '¡Ya eres Premium!',
    body:
      'Tu membresía está activa. Ahora puedes usar GymBro y GymCrush para encontrar tu dupla de entrenamiento o conectar con tu crush fitness.',
    hint:
      'Configura tus preferencias de match para empezar a descubrir perfiles y usar ambas funciones.',
    cta: 'Ir a preferencias de match',
    dismiss: 'Cerrar',
  },
  workoutsScreen: {
    client: {
      title: 'Panel de Entrenamiento',
      subheader:
        'Tus dietas, rutinas y contratos en un solo lugar para seguir tu plan.',
      items: {
        diets: {
          title: 'Mis dietas',
          description: 'Planes de alimentación asignados por tu entrenador.',
        },
        routines: {
          title: 'Mis rutinas',
          description: 'Programas de entreno según tus objetivos y nivel.',
        },
        contracts: {
          title: 'Mis contratos',
          description:
            'Estado de tus planes activos y entrenadores contratados.',
        },
      },
    },
    trainer: {
      title: 'Panel de Gestión',
      subheader:
        'Administra la actividad de tus clientes y tu negocio desde aquí.',
      items: {
        trainerDiets: {
          title: 'Dietas de clientes',
          description:
            'Crea y asigna planes de alimentación a quienes entrenas.',
        },
        trainerRoutines: {
          title: 'Rutinas de clientes',
          description: 'Diseña rutinas y haz seguimiento del progreso.',
        },
        trainerServices: {
          title: 'Mis servicios',
          description: 'Configura y publica lo que ofreces como entrenador.',
        },
        trainerPayments: {
          title: 'Mis pagos',
          description: 'Consulta ingresos y el historial de transacciones.',
        },
        trainerReviews: {
          title: 'Mis calificaciones',
          description: 'Lee las valoraciones que dejaron tus clientes.',
        },
      },
    },
  },
  premiumFeaturesScreen: {
    title: 'FITECH Premium',
    subheader: 'Herramientas exclusivas para llevar tu entrenamiento más lejos',
    badge: 'Premium',
    features: {
      workoutLog: {
        title: 'Registro de entrenos',
        description:
          'Anota cada sesión, revisa tu progreso y mantén la constancia.',
      },
      library: {
        title: 'Biblioteca de ejercicios',
        description:
          'Rutinas y movimientos organizados, del nivel básico al avanzado.',
      },
      gymBro: {
        title: 'GymBro',
        description:
          'Encuentra compañeros de entreno con tu horario y tus objetivos.',
      },
      gymCrush: {
        title: 'GymCrush',
        description:
          'Descubre entrenadores alineados a tus metas. Desliza y conéctate.',
      },
    },
  },
  common: {
    cancel: 'Cancelar',
    save: 'Guardar',
    saving: 'Guardando…',
    update: 'Actualizar',
    updating: 'Actualizando…',
    sending: 'Enviando…',
    delete: 'Eliminar',
    confirm: 'Confirmar',
    errorTitle: 'Error',
    understood: 'Entendido',
    notNow: 'Ahora no',
    yesUse: 'Sí, usar',
    active: 'Activos',
    inactive: 'Inactivos',
    tryOtherFilterHint: 'Prueba el otro filtro o vuelve más tarde',
    yesterday: 'Ayer',
    defaultUserName: 'Usuario Fitech',
    noMessagesYet: 'Aún no hay mensajes.',
    dash: '—',
  },
  listFilters: {
    routinesActiveHint: 'Filtros',
    dietsActiveHint: 'Filtros',
    contractsStatusHint: 'Filtros',
    trainerServicesHint: 'Filtros',
    completed: 'Completados',
  },
  contractsScreen: {
    title: 'Mis Contratos',
    subheader: 'Gestiona tus contratos de servicios de entrenamiento',
    emptyTitle: 'No hay contratos con este filtro',
    viewDetail: 'Ver detalle',
    leaveReview: 'Dejar reseña',
    editReview: 'Editar reseña',
    statusCompleted: 'Completado',
    statusCancelled: 'Cancelado',
    dateFrom: 'Desde {date}',
    dateUntil: 'Hasta {date}',
    dateRange: '{start} – {end}',
    amount: 'S/ {amount}',
  },
  cancelContractModal: {
    title: 'Cancelar contrato',
    intro: '¿Seguro que quieres cancelar este contrato?',
    bullets: [
      'Tu solicitud se revisará en 1–3 días hábiles.',
      'Los reembolsos siguen nuestros términos y condiciones.',
      'Perderás acceso inmediato a los recursos del entrenador.',
      'Te enviaremos un correo con el estado de tu solicitud.',
    ],
    reasonLabel: 'Motivo de cancelación',
    reasonPlaceholder: 'Cuéntanos por qué deseas cancelar…',
    reasonRequired: 'Indica un motivo para continuar.',
    attachmentLabel: 'Adjunto (opcional)',
    attachmentHint: 'PDF o imagen (JPG, PNG)',
    pickAttachment: 'Adjuntar archivo',
    removeAttachment: 'Quitar adjunto',
    attachmentUploadFailed:
      'No pudimos subir el adjunto. Inténtalo de nuevo o continúa sin archivo.',
    cancelServerError:
      'No pudimos cancelar el contrato. Si no adjuntaste un archivo, el servidor puede requerirlo por ahora — prueba con un adjunto o contacta a soporte.',
    warning: 'Esta acción no se puede deshacer',
    dismiss: 'Volver',
    confirm: 'Sí, cancelar',
  },
  completeContractModal: {
    title: 'Confirmar finalización',
    intro: '¿Estás seguro de que deseas marcar este contrato como completado?',
    bullets: [
      'Declaras que el servicio se ejecutó correctamente.',
      'Confirmas que estás satisfecho con el resultado.',
    ],
    warning: 'Esta acción no se puede deshacer',
    dismiss: 'Volver',
    confirm: 'Confirmar',
  },
  clientResourceScreen: {
    viewDetail: 'Ver detalle',
    trainerLabel: 'Entrenador',
    validityLabel: 'Vigencia del plan',
    createdAtLabel: 'Fecha de creación',
    dateFrom: 'Desde {date}',
    dateUntil: 'Hasta {date}',
    dateRange: '{start} – {end}',
    statusActive: 'Activa',
    statusInactive: 'Inactiva',
    contractTag: 'Contrato',
    downloadExcel: 'Descargar Excel',
    defaultDietTitle: 'Plan nutricional',
    defaultRoutineTitle: 'Rutina',
  },
  contractDetailScreen: {
    defaultTitle: 'Detalles del contrato',
    statusCancelled: 'Cancelado',
    statusCompleted: 'Completado',
    trainerLabel: 'Entrenador',
    validityLabel: 'Vigencia del plan',
    createdAtLabel: 'Fecha de creación',
    amountLabel: 'Monto total',
    amountValue: 'S/ {amount}',
    paymentStatusLabel: 'Estado de pago',
    descriptionLabel: 'Descripción',
    dateFrom: 'Desde {date}',
    dateUntil: 'Hasta {date}',
    dateRange: '{start} – {end}',
    completeButton: 'Completar',
    cancelButton: 'Cancelar contrato',
  },
  reviewModal: {
    title: '¿Cómo fue tu experiencia?',
    commentPlaceholder: 'Cuéntanos más sobre tu experiencia (opcional)',
    anonymousLabel: 'Publicar de forma anónima',
    anonymousHint: 'Tu nombre no será visible',
    submit: 'Enviar reseña',
    submitting: 'Enviando…',
    ratingLabels: {
      1: 'Muy malo — cuéntanos qué falló',
      2: 'Regular — hay margen de mejora',
      3: 'Bien — cumplió lo esperado',
      4: 'Muy bueno — gran experiencia',
      5: 'Excelente — no podría ser mejor',
    },
  },
  featuredTrainersSection: {
    title: 'Entrenadores destacados',
    viewProfile: 'Ver perfil',
    defaultName: 'Entrenador',
    noBio: 'Sin descripción',
  },
  trainersScreen: {
    title: 'Encuentra tu entrenador ideal',
    subheader: 'Descubre entrenadores especializados en tus objetivos fitness',
    searchHint: 'Busca por nombre del entrenador',
    searchPlaceholder: 'Buscar por nombre',
    resultCountOne: '1 entrenador encontrado',
    resultCountMany: '{count} entrenadores encontrados',
    emptyTitle: 'No encontramos entrenadores',
    emptyHint: 'Prueba con otro nombre o deja el buscador vacío para ver todos',
    viewProfile: 'Ver perfil',
    noBio: 'Sin descripción',
    defaultName: 'Entrenador',
  },
  trainerProfileScreen: {
    defaultTitle: 'Entrenador',
    role: 'Entrenador personal',
    certified: 'Entrenador certificado',
    servicesTitle: 'Servicios disponibles',
    galleryTitle: 'Galería',
    aboutTitle: 'Acerca de',
    hireService: 'Contratar servicio',
    price: 'S/ {amount}',
    contractBlockedTitle: 'Aviso',
    contractBlockedDefault:
      'Ya tienes un servicio contratado y no puedes volver a contratarlo',
  },
  contractSuccessToast: {
    title: '¡Listo!',
    message: 'Su contrato ha sido generado satisfactoriamente.',
    chatCta: 'Chatear con tu entrenador',
  },
  routinesScreen: {
    title: 'Mis Rutinas de Entrenamiento',
    subheader: 'Organiza, sigue y mejora tus sesiones de entrenamiento',
    emptyTitle: 'No hay rutinas con este filtro',
  },
  dietsScreen: {
    title: 'Mis Planes Nutricionales',
    subheader: 'Dietas personalizadas para alcanzar tus objetivos de salud',
    emptyTitle: 'No hay planes con este filtro',
  },
  chatsScreen: {
    title: 'Chats',
    subheader:
      'Mantén el contacto con tus gymcrush y gymbros cuando lo necesites',
    loading: 'Cargando chats…',
    emptyTitle: 'Aún no tienes conversaciones activas',
    deleteTitle: '¿Eliminar conversación?',
    deleteMessage:
      'Se eliminará el chat con {name}. Esta acción no se puede deshacer.',
    deleteError: 'No se pudo eliminar la conversación.',
  },
  macrosCalculatorScreen: {
    title: '¿Cuántos gramos tiene tu antojo?',
    subheader:
      'Descubre si estás alimentando músculo, energía... o puro gustito.',
    searchPlaceholder: 'Buscar comida',
    categoryLabel: 'Categoría',
    categoryPlaceholder: 'Todas las categorías',
    searchHint: 'Explora el catálogo o filtra por categoría y nombre.',
    searchEmpty: 'No encontramos alimentos para esa búsqueda.',
    searchResults: 'Alimentos',
    selectedTitle: 'Tu selección',
    viewMacrosButton: 'Ver macros',
    addFood: 'Agregar',
    addedFood: 'Agregado',
    removeFood: 'Quitar',
    calculateTitle: '¿Cuánto comiste?',
    calculateSubheader:
      'Ajusta las porciones para obtener tu desglose de macros.',
    noSelectionBanner:
      'Todavía no elegiste ningún alimento. Agrega uno para calcular tus macros.',
    showResultsButton: 'Mostrar resultados',
    portionsSection: 'Tus porciones',
    gramsPerPortion: '{grams} por porción',
    portionsGrams: '{portions} porc. · {grams}',
  },
  foodUnitTypes: {
    grams: 'Gramos',
    unit: 'Unidad/Pieza',
    scoop: 'Scoop',
    cup: 'Taza',
    tablespoon: 'Cucharada',
    teaspoon: 'Cucharadita',
    piece: 'Pieza',
    ml: 'Mililitros',
  },
  notificationsScreen: {
    title: 'Notificaciones',
    subheader: 'Novedades de tus dietas, rutinas y contratos',
    markAllRead: 'Marcar todo como leído',
    loading: 'Cargando notificaciones…',
    emptyTitle: 'Estás al día',
    emptyHint: 'No tienes notificaciones pendientes',
  },
  subscriptionScreen: {
    title: 'Mi Suscripción',
    subheader: 'Gestiona tu membresía premium',
    activeTitle: 'Suscripción Activa',
    activeSubtitle:
      'Tu membresía premium está activa y funcionando correctamente.',
    infoTitle: 'Información de Suscripción',
    infoSubtitle: 'Detalles de tu membresía actual',
    contractInfoTitle: 'Información del Contrato',
    contractInfoSubtitle: 'Detalles de tu contrato con el entrenador',
    startDateLabel: 'Fecha de inicio',
    endDateLabel: 'Fecha de finalización',
    membershipTypeLabel: 'Tipo de Membresía',
    trainerLabel: 'Entrenador',
    paymentHistoryTitle: 'Ver Historial de Pagos',
    paymentHistoryCardTitle: 'Historial de Pagos',
    paymentHistoryCardSubtitle: 'Últimos pagos realizados',
    emptyPayments: 'Aún no hay pagos registrados.',
    paymentMethods: {
      CONTRACT_PAYMENT: 'Pago de Contrato',
      STRIPE: 'Stripe',
    },
  },
  exercisesScreen: {
    title: 'Mi Registro de Entrenamientos',
    subheader: 'Lleva el control de tus workouts y alcanza tus metas fitness',
    filterTitle: 'Filtro por grupo muscular',
    filterHint: 'Toca un grupo para filtrar los entrenamientos del mes',
    workoutDay: {
      subheader: 'Entrenamientos registrados',
      loading: 'Cargando entrenamientos…',
      emptyTitle: 'Sin entrenamientos este día',
      emptyHint:
        'Registra tus ejercicios con el botón de abajo y lleva tu progreso al día.',
    },
  },
  profileScreen: {
    userTypeTrainer: 'Trainer',
    userTypeUser: 'Usuario',
    premiumByContract: 'Premium (Con Contrato)',
    premiumByPayment: 'Premium (Por Pago)',
  },
  fitnessGoalsScreen: {
    title: 'Objetivos Fitness',
    subheader: 'Selecciona tus metas para recomendaciones personalizadas',
    updateButton: 'Actualizar',
    cancelButton: 'Cancelar',
    successTitle: '¡Listo!',
    successMessage: 'Tus objetivos fitness se actualizaron correctamente.',
    errorTitle: 'No se pudo actualizar',
    errorMessage: 'Intenta de nuevo en unos momentos.',
  },
  profileMenu: {
    sections: {
      profile: 'Perfil',
      fitness: 'Fitness y preferencias',
      account: 'Cuenta',
      help: 'Ayuda',
    },
    items: {
      personalInfo: 'Información personal',
      photoGallery: 'Galería de fotos',
      changePassword: 'Cambiar contraseña',
      fitnessGoals: 'Objetivos fitness',
      matchPreferences: 'Preferencias de match',
      subscription: 'Suscripción',
      notifications: 'Notificaciones',
      support: 'Soporte',
      testTools: 'Testing tools',
      deleteAccount: 'Eliminar cuenta',
      logout: 'Logout',
    },
  },
  imageGalleryScreen: {
    title: 'Gestiona tus fotos',
    profilePhotoBadge: 'Foto de perfil',
    noProfilePhoto: 'Sin foto de perfil',
    changeAvatarButton: 'Cambiar avatar',
    updatingAvatar: 'Actualizando…',
    addPhotoLabel: 'AGREGAR FOTO',
    bannerTitle: 'Haz que tu perfil destaque',
    bannerText:
      'Sube hasta {max} fotos que muestren tu estilo, resultados y experiencia como trainer.',
    progressMaxReached: 'Has subido el máximo de fotos permitidas',
    progressOneRemaining: 'Te falta 1 foto para completar tu galería',
    progressManyRemaining:
      'Te faltan {remaining} fotos para completar tu galería',
    profilePhotoError: 'No se pudo actualizar tu foto de perfil.',
    confirmProfileTitle: 'Foto de perfil',
    confirmProfileFirstMessage:
      'Esta es tu primera foto. ¿Quieres usarla como tu foto de perfil?',
    confirmProfileMessage:
      '¿Quieres usar esta foto como tu nueva foto de perfil?',
    limitReachedTitle: 'Límite alcanzado',
    limitReachedMessage: 'Solo puedes subir hasta 10 fotos.',
    permissionRequiredTitle: 'Permiso requerido',
    uploadErrorFallback: 'No se pudo subir la foto. Inténtalo de nuevo.',
    processImageErrorFallback: 'No se pudo procesar la imagen seleccionada.',
    noPhotosTitle: 'Sin fotos',
    noPhotosMessage: 'Sube al menos una foto para poder elegir tu avatar.',
    pickExistingPhoto: 'Elegir de tus fotos',
    uploadNewPhoto: 'Subir nueva foto',
    changeAvatarTitle: 'Cambiar avatar',
    changeAvatarMessageUpload: 'Elige una foto existente o sube una nueva',
    changeAvatarMessagePick: 'Elige una de tus fotos de la galería',
    deleteProfilePhotoTitle: 'Eliminar foto de perfil',
    deletePhotoTitle: 'Eliminar foto',
    deleteProfilePhotoMessage:
      'Esta es tu foto de perfil. Si la eliminas, deberás elegir otra.',
    deletePhotoMessage: '¿Seguro que quieres eliminar esta foto?',
    deletePhotoError: 'No se pudo eliminar la foto.',
  },
};
